name: Build Immortalwrt

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    name: Build ${{ matrix.target }}-${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [snapshots, 23.05-SNAPSHOT]
        target: [xiaomi_ax3600, xiaomi_ax3600-stock, friendlyarm_nanopi-r5c]
        include:
          - target: xiaomi_ax3600
            vendor: qualcommax
            arch: ipq807x
            env_file: ax3600.env
            conf_dir: qualcommax
          - target: xiaomi_ax3600-stock
            vendor: qualcommax
            arch: ipq807x
            env_file: ax3600-stock.env
            conf_dir: qualcommax
          - target: friendlyarm_nanopi-r5c
            vendor: rockchip
            arch: armv8
            env_file: r5c.env
            conf_dir: rockchip

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3

      - name: Load env file
        run: |
          cat ${{ matrix.conf_dir }}/${{ matrix.env_file }} >> $GITHUB_ENV

      - name: Build images
        run: |
          echo ${{ env.PROFILE }}
          echo ${{ env.PACKAGES }}
          echo ${{ env.FILES }}
          sf=""
          pf=${{ matrix.vendor }}-${{ matrix.arch }}
          vendor=${{ matrix.vendor }}
          arch=${{ matrix.arch }}
          if [ ${{ matrix.version }} != "snapshots" ]; then
            if [ "${vendor}" == "qualcommax" ]; then
              vendor="ipq807x"
              arch="generic"
            fi
            pf=${{ matrix.version }}-${vendor}-${arch}
            sf="releases/${sf}"
          fi
          wget https://downloads.immortalwrt.org/${sf}${{ matrix.version }}/targets/${vendor}/${arch}/immortalwrt-imagebuilder-${pf}.Linux-x86_64.tar.xz -O ib.tar.xz
          mkdir ib
          tar xf ib.tar.xz --strip-components=1 -C ib
          cp -a ${{matrix.conf_dir}}/files ib/
          cd ib
          make image PROFILE=${{ env.PROFILE }} PACKAGES=${{ env.PACKAGES }} FILES=${{ env.FILES }}
          cd -

      - name: Publishing to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-${{ matrix.version }}
          path: |
            ib/bin/targets/*/*/*
