name: Build Immortalwrt

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: xiaomi_ax3600
            vendor: qualcommax
            arch: ipq807x
            env_file: ax3600.env
            conf_dir: qualcommax
          - target: xiaomi_ax3600-stock
            vendor: qualcommax
            arch: ipq807x
            env_file: ax3600-stock.env
            conf_dir: qualcommax
          - target: friendlyarm_nanopi-r5c
            vendor: rockchip
            arch: armv8
            env_file: r5c.env
            conf_dir: rockchip

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3

      - name: Load env file
        run: |
          cat ${{ matrix.conf_dir }}/${{ matrix.env_file }} >> $GITHUB_ENV

      - name: Build images
        run: |
          echo ${{ env.PROFILE }}
          echo ${{ env.PACKAGES }}
          echo ${{ env.FILES }}
          wget -q https://downloads.immortalwrt.org/snapshots/targets/${{ matrix.vendor }}/${{ matrix.arch }}/immortalwrt-imagebuilder-${{ matrix.vendor }}-${{ matrix.arch }}.Linux-x86_64.tar.xz -O ib.tar.xz
          mkdir ib
          tar xf ib.tar.xz --strip-components=1 -C ib
          cp -a ${{matrix.conf_dir}}/files ib/
          cd ib
          make image PROFILE=${{ env.PROFILE }} PACKAGES=${{ env.PACKAGES }} FILES=${{ env.FILES }}
          cd -

      - name: Publishing to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            ib/bin/targets/*/*/*
